{% set version = "1.0.0" %}

package:
  name: mindboggle
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/akeshavan/mindboggle/archive/{{ version }}.tar.gz
  md5: ba2e02f85148d45bdd513f66f6ea5693

build:
  number: 0
  script: python setup.py install

requirements:
  build:
    - python
    - nipype

  run:
    - python
    - nipype

test:
  # Python imports
  imports:
    - mindboggle

about:
  home: https://github.com/nipy/nipype
  license: Apache 2.0
  summary: 'Nipype, an open-source, community-developed initiative under the
  umbrella of NiPy, is a Python project that provides a uniform interface to
  existing neuroimaging software and facilitates interaction between these
  packages within a single workflow. Nipype provides an environment that
  encourages interactive exploration of algorithms from different packages
  (e.g., SPM, FSL, FreeSurfer, AFNI, Slicer, ANTS), eases the design of
  workflows within and between packages, and reduces the learning curve
  necessary to use different packages. Nipype is creating a collaborative
  platform for neuroimaging software development in a high-level language and
  addressing limitations of existing pipeline systems.'

extra:
  recipe-maintainers:
    - chrisfilo
    - satra
