travis:
  secure:
    BINSTAR_TOKEN: EuBmVBs1h/WwG5M//ulAL+p9l3F+i8Atay4f4Bc71oFiyDrMe3rFKPSyPQba3SkUZ7f1Q5pDe0evdGUvvZetDnUUwQgBnKt8zlpP4EhprEZYG+I32K1DamSb2bJphIksdyTOcZHMKfG2eXwkhSwYQpai+OCk8aZGiY+s/UnSokzH/RUa7seD6TvMjxowaO5aCPZr+p8Fg2+uoJBW8g7H1QtASWGjwa4x2CioDZ5LBxyrge8n5WUJG/9or7ymZzArVClYTkBeNkNKGxxje5k4GdugaFNNiciA2sw+bEZgKpM4ZFOEPVNXJiiAYicT0Y2Y2p26n8XbhJ9Z+t3uDQDtegJGuBhOauUfPnAWPjeJIVZUfoQNehjqeQoXVnuAg623Fkaz9hq/mLdWHMh7cKu+9F5tvLo3Sd+yiCgFRXox7VEPke8t3BGwhFR9s9HiJhih20RlMEC2Gw/4HKDG2jB2rcj7HIsAE7PnOqDskCYb3KHq6Pb+LbRZgL025L3tJ0xXB+HG+s6LX11MWElj91WhZVS5vg4rjg9QDj926czYQXNyaQ+1BDkT59ysBcfhS3I2qp7aDLqopsRkR7gmnA4ZPXhWLArXUkXubSuW/MoCwr3SsCfzcGDJAUcsn+P5nxwdFLwdRczpjc/BFpfHxNlta2DlL9ntUg5QigohTmxortE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
